packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@firebase/util"
  - "@scarf/scarf"
  - sqlite3

onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/engines"
  - esbuild
  - prisma
  - protobufjs
