import { Body, Controller, Get, Headers, Post, Patch, Param, Query, Req } from "@nestjs/common";import crypto from "node:crypto";import { prisma } from "@webpilot/database";import { SecretVault,TaskQueue } from "@webpilot/gcp";import { requireWorkspace } from "../common/context.js";import { Public } from "../common/public.decorator.js";
function verifySlack(raw:string,ts:string,sig:string){const secret=process.env.SLACK_SIGNING_SECRET||"";const expected="v0="+crypto.createHmac("sha256",secret).update(`v0:${ts}:${raw}`).digest("hex");return !!secret&&crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(sig||""));}
@Controller("integrations") export class IntegrationsController{
 @Get() async list(@Req() req:any,@Query("workspaceId") workspaceId?:string){const m=await requireWorkspace(req.user.id,workspaceId);return prisma.integration.findMany({where:{workspaceId:m.workspaceId}})}
 @Patch(":id") async update(@Req() req:any,@Param("id") id:string,@Body() body:any){const i=await prisma.integration.findUniqueOrThrow({where:{id}});await requireWorkspace(req.user.id,i.workspaceId,["OWNER","ADMIN"]);return prisma.integration.update({where:{id},data:{metadata:{...((i.metadata as any)||{}),...body.metadata}}});}
 @Post("slack/connect") async slackConnect(@Req() req:any,@Body() body:any){await requireWorkspace(req.user.id,body.workspaceId,["OWNER","ADMIN"]);return{url:`https://slack.com/oauth/v2/authorize?client_id=${encodeURIComponent(process.env.SLACK_CLIENT_ID||"")}&scope=commands,chat:write,app_mentions:read&redirect_uri=${encodeURIComponent(process.env.SLACK_REDIRECT_URI||"")}&state=${encodeURIComponent(body.workspaceId)}`};}
 @Public() @Get("slack/callback") async callback(@Query("code") code:string,@Query("state") workspaceId:string){const r=await fetch("https://slack.com/api/oauth.v2.access",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:process.env.SLACK_CLIENT_ID||"",client_secret:process.env.SLACK_CLIENT_SECRET||"",redirect_uri:process.env.SLACK_REDIRECT_URI||""})});const data:any=await r.json();if(!data.ok) throw new Error(data.error);const ref=await new SecretVault().put(`slack-${workspaceId}`,JSON.stringify({accessToken:data.access_token}));await prisma.integration.upsert({where:{id:`slack-${workspaceId}`},update:{status:"CONNECTED",metadata:{team:data.team},secretManagerRef:ref},create:{id:`slack-${workspaceId}`,workspaceId,provider:"SLACK",status:"CONNECTED",displayName:data.team?.name||"Slack",metadata:{team:data.team},secretManagerRef:ref}});return{ok:true};}
 @Public() @Post("slack/command") async command(@Req() req:any,@Headers("x-slack-request-timestamp") ts:string,@Headers("x-slack-signature") sig:string){const raw=typeof req.body==="string"?req.body:new URLSearchParams(req.body).toString();if(!verifySlack(raw,ts,sig)) return{response_type:"ephemeral",text:"Invalid signature"};const body=typeof req.body==="string"?Object.fromEntries(new URLSearchParams(req.body)):req.body;const agent=await prisma.agent.findFirst({where:{name:{contains:String(body.text||""),mode:"insensitive"}}});if(!agent)return{response_type:"ephemeral",text:"Agent not found"};const run=await prisma.run.create({data:{workspaceId:agent.workspaceId,agentId:agent.id,versionId:agent.activeVersionId,triggerType:"SLACK",status:"QUEUED",executionMode:agent.activeVersionId?"FAST_PATH":"DISCOVERY",idempotencyKey:`slack-${crypto.randomUUID()}`}});await new TaskQueue().enqueueRun(run.id);return{response_type:"in_channel",text:`WebPilot started ${agent.name}. Run ${run.id}`};}
}
